version: 0.5.1
content:
  l1PhaseIPFJetTree/L1PhaseIPFJetTree:
    name: L1PhaseIPFJetTree
    optional: false
    branches:
      L1PhaseIPFJet.ak4PFJetEt:
        aliases:
        - event.L1PhaseIPFJet_ak4PFJetEt
      L1PhaseIPFJet.ak4PFJetEta:
        aliases:
        - event.L1PhaseIPFJet_ak4PFJetEta
      L1PhaseIPFJet.ak4PFJetHt:
        aliases:
        - event.L1PhaseIPFJet_ak4PFJetHt
      L1PhaseIPFJet.ak4PFJetMHT:
        aliases:
        - event.L1PhaseIPFJet_ak4PFJetMHT
      L1PhaseIPFJet.ak4PFJetPhi:
        aliases:
        - event.L1PhaseIPFJet_ak4PFJetPhi
      L1PhaseIPFJet.genJetEta:
        aliases:
        - event.L1PhaseIPFJet_genJetEta
      L1PhaseIPFJet.genJetHt:
        aliases:
        - event.L1PhaseIPFJet_genJetHt
      L1PhaseIPFJet.genJetM:
        aliases:
        - event.L1PhaseIPFJet_genJetM
      L1PhaseIPFJet.genJetMHT:
        aliases:
        - event.L1PhaseIPFJet_genJetMHT
      L1PhaseIPFJet.genJetPhi:
        aliases:
        - event.L1PhaseIPFJet_genJetPhi
      L1PhaseIPFJet.genJetPt:
        aliases:
        - event.L1PhaseIPFJet_genJetPt
      L1PhaseIPFJet.genMet:
        aliases:
        - event.L1PhaseIPFJet_genMet
      L1PhaseIPFJet.nAK4PFJets:
        aliases:
        - event.L1PhaseIPFJet_nAK4PFJets
      L1PhaseIPFJet.nGenJet:
        aliases:
        - event.L1PhaseIPFJet_nGenJet
      L1PhaseIPFJet.nPhaseIPFJets:
        aliases:
        - event.L1PhaseIPFJet_nPhaseIPFJets
      L1PhaseIPFJet.pfMet:
        aliases:
        - event.L1PhaseIPFJet_pfMet
      L1PhaseIPFJet.phaseIPFJetEt:
        aliases:
        - event.L1PhaseIPFJet_phaseIPFJetEt
      L1PhaseIPFJet.phaseIPFJetEta:
        aliases:
        - event.L1PhaseIPFJet_phaseIPFJetEta
      L1PhaseIPFJet.phaseIPFJetHt:
        aliases:
        - event.L1PhaseIPFJet_phaseIPFJetHt
      L1PhaseIPFJet.phaseIPFJetMET:
        aliases:
        - event.L1PhaseIPFJet_phaseIPFJetMET
      L1PhaseIPFJet.phaseIPFJetMETHF:
        aliases:
        - event.L1PhaseIPFJet_phaseIPFJetMETHF
      L1PhaseIPFJet.phaseIPFJetMHT:
        aliases:
        - event.L1PhaseIPFJet_phaseIPFJetMHT
      L1PhaseIPFJet.phaseIPFJetPhi:
        aliases:
        - event.L1PhaseIPFJet_phaseIPFJetPhi
